# Deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: joelneyo/inventory-service:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-inventory-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-inventory-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: inventory-service-config

---

# Configurations

apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  application-k8s.properties: |
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.url=jdbc:mysql://mysql-inventory-service:3306/inventory-service
    spring.jpa.hibernate.ddl-auto=create-drop
    server.port=80
    spring.application.name=inventory-service
    spring.datasource.username=${MYSQL_USERNAME}
    spring.datasource.password=${MYSQL_PASSWORD}

---

# Service

apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP



