apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.properties: |
    spring.application.name=api-gateway
    logging.level.root=INFO
    logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
    logging.level.org.springframework.cloud.gateway=TRACE

    spring.cloud.gateway.routes[0].id=product-service
    spring.cloud.gateway.routes[0].uri=http://product-service:8082
    spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product
    
    spring.cloud.gateway.routes[1].id=order-service
    spring.cloud.gateway.routes[1].uri=http://order-service:8081
    spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: joelneyo/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          args: [ "--spring.config.location=file:/config/application.properties" ]
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config

---

# service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
