# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  standalone.xml: |
    <configuration>
      ...
      # Add your Keycloak configuration here
      ...
    </configuration>

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:latest
          env:
            - name: KEYCLOAK_USER
              value: "<your-admin-username>"
            - name: KEYCLOAK_PASSWORD
              value: "<your-admin-password>"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - name: http
              containerPort: 8181
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: config-volume
              mountPath: /opt/jboss/keycloak/standalone/configuration/standalone.xml
              subPath: standalone.xml
      volumes:
        - name: config-volume
          configMap:
            name: keycloak-config

---

# Service

apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
