# config
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  application-k8s.properties: |
    spring.data.mongodb.host=mongodb-service
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=product-service
    spring.data.mongodb.username=${MONGO_USERNAME}
    spring.data.mongodb.password=${MONGO_PASSWORD}
    spring.application.name=product-service
    server.port=0

---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: joelneyo/product-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: product-service-config

---
# service
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
