apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce-app
  region: ap-southeast-1

nodeGroups:
  - name: ecommerce
    instanceType: t2.small
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 10 # 10GB

